# **Numpy Array**

In [ ]:
import numpy as np

my_list= [1,2,3,4]

np.array(my_list)

array([1, 2, 3, 4])

In [ ]:
nested_list = [[1,2],[3,4],[5,6]]
nested_list

[[1, 2], [3, 4], [5, 6]]

In [ ]:
np.array(nested_list )

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2) #(start,end,step)

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(3)

array([0.59332606, 0.98996405, 0.56678905])

In [ ]:
np.random.rand(3,4)

array([[0.03025933, 0.68767372, 0.81528126, 0.7341352 ],
       [0.44154444, 0.1384657 , 0.27150826, 0.73537329],
       [0.18668919, 0.26750366, 0.83408037, 0.54431493]])

In [ ]:
np.random.randn(3)

array([ 1.93509601, -0.4001221 ,  1.5332298 ])

In [ ]:
np.random.randn(3,5)

array([[ 0.33281134,  1.45263868, -1.37913839, -1.15707992,  0.53073781],
       [ 0.71002061,  0.63532886,  0.05182091,  0.19116536, -0.26857509],
       [ 0.89107726,  0.56383168,  0.73114306, -0.52612594, -1.33481231]])

In [ ]:
np.random.randint(1,100)

45

In [ ]:
np.random.randint(1,100,10)

array([53, 27, 98, 80, 66, 92,  9, 93, 63, 46])

In [ ]:
np.random.randint(1,100,(2,3))

array([[42, 10, 38],
       [56, 96, 47]])

In [ ]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [ ]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr= np.random.randint(0,50,10)
ranarr

array([ 1, 20, 32, 11, 21, 43, 24, 48, 26, 41])

In [ ]:
arr.shape

(25,)

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr


array([ 1, 20, 32, 11, 21, 43, 24, 48, 26, 41])

In [ ]:
ranarr.max()

48

In [ ]:
ranarr.min()

1

In [ ]:
ranarr.mean()

26.7

In [ ]:
ranarr.argmin()

0

In [ ]:
ranarr.dtype

dtype('int64')

In [ ]:
myarr= np.random.rand(4)

In [ ]:
myarr

array([0.04666566, 0.97375552, 0.23277134, 0.09060643])

In [ ]:
myarr.dtype

dtype('float64')

# **Numpy Index**

In [2]:
import numpy as np


In [3]:
arr =np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[1:5:2]

array([1, 3])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr = np.arange(0,11)

In [14]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_arr[:] = 99

In [17]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [19]:
arr_copy =arr.copy()

In [20]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [21]:
arr_copy[:] = 100

In [22]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [24]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d.shape


(3, 3)

In [31]:
arr_2d[0,2]

15

In [33]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [35]:
arr= np.arange(1,11)

In [36]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [38]:
bool_arr = arr>4

In [39]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

# **Numpy Operations**

In [41]:
import numpy as np

In [42]:
arr =np.arange(0,10)

In [43]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
arr -2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [46]:
arr + arr # same shape

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
arr / arr

<ipython-input-48-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [50]:
1/ arr

<ipython-input-50-d25465d7253e>:1: RuntimeWarning: divide by zero encountered in divide
  1/ arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [51]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [53]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [54]:
np.log(arr)

<ipython-input-54-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [55]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr.sum()

45

In [57]:
arr.mean()

4.5

In [58]:
arr.max()

9

In [59]:
arr.min()

0

In [60]:
arr.var()

8.25

In [61]:
arr.std()

2.8722813232690143

In [63]:
arr_2d = np.arange(0,25).reshape(5,5)

In [64]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [66]:
arr_2d.shape

(5, 5)

In [67]:
arr_2d.sum()

300

In [71]:
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [74]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [69]:
arr_2d.max()


24

In [70]:
arr_2d.min()

0

In [75]:
arr_2d.mean()

12.0

In [76]:
arr_2d.mean(axis=0)

array([10., 11., 12., 13., 14.])

# **Numpy exercises**

In [77]:
import numpy as np

In [78]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [79]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [81]:
np.ones(10) +4

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [82]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [88]:
arr = np.arange(10,51)


In [89]:
arr[arr%2==0]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [90]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [94]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [97]:
np.random.rand(1)

array([0.7403032])

In [99]:
np.random.randn(25)

array([-0.07564889,  0.49234378,  0.81020439,  0.54044934, -0.01344145,
        0.29109756, -1.48672438,  0.15117515,  0.01751888, -0.58590508,
       -1.04530894,  0.43628816,  0.64316712,  1.35171847, -0.43647558,
       -0.05926432,  0.20619402, -0.15089409, -0.67008274, -0.0169432 ,
       -0.68113626,  0.7386109 , -0.48248936, -1.01252192, -0.03384558])

In [103]:
arr = np.arange(1,101)/100
arr.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [104]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [105]:
arr =np.arange(1,26)

In [107]:
mat= arr.reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [110]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [112]:
mat[3,4]

20

In [117]:
a=mat[:3,1]
a.reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [118]:
mat[:3,1:2] # to maintain same dimension shape

array([[ 2],
       [ 7],
       [12]])

In [120]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [121]:
mat[4]

array([21, 22, 23, 24, 25])

In [125]:
mat[3:]


array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [127]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [128]:
mat.sum()

325

In [131]:
mat.std()

7.211102550927978

In [132]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [137]:
np.random.seed(101)
np.random.rand(1)

array([0.51639863])